name = "hercules-form-handler-fr-prod"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
SENDER_EMAIL = "info@hercules-merchandising.fr"
SENDER_NAME = "Hercules Merchandising"
COMPANY_EMAIL = "info@hercules-merchandising.fr"
R2_PUBLIC_URL = "https://pub-5016d733f4d246a5b2aaa7391f080655.r2.dev"
PRODUCT_SYNC_URL = "https://hercules-product-sync-fr-prod.gilles-86d.workers.dev"

[[routes]]
pattern = "hercules-merchandising.fr/api/*"
zone_name = "hercules-merchandising.fr"

[[r2_buckets]]
binding = "FORM_UPLOADS"
bucket_name = "hercules-fr-form-uploads-prod"
